name: Test and Build

on: [push, pull_request]

jobs:

  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [8, 11, 12, 13]
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.node-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.node-version }}

      - name: Run tests
        run: ./gradlew test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Run tests
        run: ./gradlew test

      - name: Build skript-parser
        run: ./gradlew build

      - name: Upload Nightly Build
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: skript-nightly
          path: build/libs/skript-parser.jar