name: Build, Test & Upload

on:
  push:
  pull_request:
    branches-ignore:
      - master

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [11, 13]
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build project
        run: gradle build

      - name: Run tests
        run: gradle test

      - name: Upload Nightly Build
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: skript-nightly
          path: build/libs/**
